@startuml DiagramaSequencia

skinparam classAttributeIconSize 0
skinparam classFontStyle bold
skinparam class {
  BackgroundColor LightYellow
  BorderColor DarkOrange
  ArrowColor DarkGray
}
skinparam linetype ortho

actor "Pesquisador" as p
boundary "BoundaryProjeto" as b
control "ControlProjeto" as c

p -> b : submeterProjeto()
activate b

b -> c : solicitarFormulario()
activate c

c --> b : exibirFormulario()
deactivate c

b --> p : telaSubmissao()
deactivate b

p -> b : enviarDadosProjeto(dados)
activate b

b -> c : enviarProjeto(dados)
activate c

c --> Projeto : registrarProjeto() <<create>>
activate Projeto

c -> Projeto : alterarSituacao("Enviado")

Projeto --> c : confirmacao
deactivate Projeto

c --> b
deactivate c

b --> p
deactivate b

@enduml
